name: Java CI/CD with Gradle

# Trigger on pushes and pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Set up Gradle
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3

    # Step 4: Make Gradle wrapper executable (fix permission issue on Linux)
    - name: Make Gradle wrapper executable
      run: chmod +x gradlew

    # Step 5: Build the project
    - name: Build with Gradle
      run: ./gradlew build

    # Step 6: Run unit tests
    - name: Run tests
      run: ./gradlew test

    # Step 7: Optional - Build Docker image (requires Dockerfile in project root)
    - name: Build Docker image
      if: success()  # only run if build & tests pass
      run: |
        docker build -t my-gradle-app:latest .
